# Generated by Django 4.1.2 on 2022-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
