# Generated by Django 4.1.2 on 2022-12-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePages', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
