# Generated by Django 4.1.2 on 2022-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePages', '0003_alter_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='album_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
